### ISSUE TITLE
你公司干什么的

### ISSUE THREAD

**Issue by ugksoft** [phith0n/Mind-Map#6]
你公司干什么的

收集了这么多东西, 个人不至于这么多,这么细的,还有时间去画整理...

好奇,随便问问,没其它意思

**Comment by phith0n** [comment]
大部分是在以前乌云社区收集的。

从此处可以看出，没有乌云，对整个安全圈的影响。

**Comment by ugksoft** [comment]
哎, 那拉皮条的,拉了10多年了,杀千刀!!
