### ISSUE TITLE
翻譯成西班牙語

### ISSUE THREAD

**Issue by yhojann-cl** [phith0n/Mind-Map#9]
您好，您可以將地圖翻譯成西班牙語或以純文本形式發布資源以幫助翻譯嗎？

**Comment by Str0ngX** [comment]
已收到，谢谢！

**Comment by phith0n** [comment]
@yhojann-cl 

Sorry I' afraid cannot. Most of the files are collected from Chinese security community, not created by myself.

So I don't have the source files, it's hard to translate.

Another security repository that is good for study recommendly: <https://github.com/vulhub/vulhub>, you can take a look.
